// Converted from demos/home.html; behaviour lives in src/site.js.
export default function Menu() {
  return (
    <div className="menu" id="menu" role="dialog" aria-modal="true" aria-label="Site index" inert>      {' '}
<div className="menu-top"><a className="brand" href="#top" data-close=""><img src="/brand/mark-128.png" alt="" /><b>{"AVOFLARE"}</b></a><button className="menu-close" id="menuClose" type="button">{"Close "}<span className="x" aria-hidden="true" /></button></div>      {' '}
<div className="menu-body">        {' '}
<ol className="menu-list" id="menuList"><li style={{"--i": "0"}}><a href="#problem" data-img="0"><span className="n">{"01"}</span><span className="t">{"The problem"}</span><span /><span className="d">{"Problem Statement 26054 and where we stand on A–F"}</span></a></li><li style={{"--i": "1"}}><a href="#how" data-img="1"><span className="n">{"02"}</span><span className="t">{"How it works"}</span><span /><span className="d">{"The fault signal, the lost link and the flowchart"}</span></a></li><li style={{"--i": "2"}}><a href="#built" data-img="2"><span className="n">{"03"}</span><span className="t">{"What we built"}</span><span /><span className="d">{"Dashboard, simulation, CAN telemetry and fault runs"}</span></a></li><li style={{"--i": "3"}}><a href="#whatsnew" data-img="3"><span className="n">{"04"}</span><span className="t">{"What's new"}</span><span /><span className="d">{"Physics and data, explained alerts, the engineer decides"}</span></a></li><li style={{"--i": "4"}}><a href="#demo" data-img="4"><span className="n">{"05"}</span><span className="t">{"Demo"}</span><span /><span className="d">{"Watch the full loop, start to finish"}</span></a></li><li style={{"--i": "5"}}><a href="#security" data-img="5"><span className="n">{"06"}</span><span className="t">{"Security"}</span><span /><span className="d">{"Trusted when it counts: layers, trust engine, sealed links"}</span></a></li><li style={{"--i": "6"}}><a href="#roadmap" data-img="6"><span className="n">{"07"}</span><span className="t">{"Roadmap"}</span><span /><span className="d">{"From simulation to the flight line"}</span></a></li><li style={{"--i": "7"}}><a href="#why" data-img="7"><span className="n">{"08"}</span><span className="t">{"Why AVOFLARE"}</span><span /><span className="d">{"The case for adopting it, and why now"}</span></a></li></ol>        {' '}
<figure className="menu-media" aria-hidden="true"><img src="/media/img/runway-wash-1600.webp" alt="" loading="lazy" className="on" /><img src="/media/img/runway-soft-1920.webp" alt="" loading="lazy" /><img src="/media/built/gcs-operator-960.webp" alt="" loading="lazy" /><img src="/media/img/clouds-sunset-1200.webp" alt="" loading="lazy" /><img src="/media/v/demo-placeholder.webp" alt="" loading="lazy" /><img src="/media/img/engine-1200.webp" alt="" loading="lazy" /><img src="/media/img/station-1200.webp" alt="" loading="lazy" /><img src="/media/img/runway-night-1200.webp" alt="" loading="lazy" /><figcaption id="menuCap">{"Problem Statement 26054 and where we stand on A–F"}</figcaption></figure>        {' '}
</div>      {' '}
<div className="menu-foot"><span>{"Problem Statement 26054 · simulated data · AI stages designed, not yet running"}</span><span><a href="?intro">{"Replay intro"}</a></span></div>      {' '}
</div>
  );
}
