// Converted from demos/home.html; behaviour lives in src/site.js.
export default function Roadmap() {
  return (
    <section className="rm" id="roadmap" data-t="6600" aria-labelledby="h-rm">      {' '}
<div className="wrap">        {' '}
<div className="rm-head">          {' '}
<div><p className="bt-eyebrow rv">{"07 · ROADMAP"}</p><h2 id="h-rm" className="rv">{"From simulation "}<em>{"to the flight line."}</em></h2></div>          {' '}
<p className="rv" style={{"--i": "1"}}>{"The prototype runs in simulation. Next it moves onto real hardware, a real engine and a real ground station."}</p>          {' '}
</div>        {' '}
<div className="rm-body" id="rmBody">          {' '}
<div className="rm-prof" aria-hidden="true">            {' '}
<svg viewBox="0 0 1200 210" preserveAspectRatio="none" id="rmSvg"><defs><linearGradient id="rmFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f8ccc" stopOpacity=".28" /><stop offset="1" stopColor="#4f8ccc" stopOpacity="0" /></linearGradient><clipPath id="rmPast"><rect id="rmPastR" x="0" y="0" width="0" height="210" /></clipPath><clipPath id="rmFutClip"><rect id="rmFutR" x="0" y="0" width="1200" height="210" /></clipPath></defs><g className="rm-hl"><rect data-k="0" x="0" y="0" width="300" height="190" /><rect data-k="1" x="300" y="0" width="300" height="190" /><rect data-k="2" x="600" y="0" width="300" height="190" /><rect data-k="3" x="900" y="0" width="300" height="190" /></g><line className="rm-ground" x1="0" y1="190" x2="1200" y2="190" /><g className="rm-div"><line x1="300" y1="10" x2="300" y2="190" /><line x1="600" y1="10" x2="600" y2="190" /><line x1="900" y1="10" x2="900" y2="190" /></g><path className="rm-area" id="rmArea" clipPath="url(#rmPast)" /><path className="rm-fut" id="rmFut" clipPath="url(#rmFutClip)" /><path className="rm-past" id="rmPastP" clipPath="url(#rmPast)" /></svg>            {' '}
<span className="rm-node" data-k="0" /><span className="rm-node" data-k="1" /><span className="rm-node" data-k="2" /><span className="rm-node" data-k="3" />            {' '}
<span className="rm-ac" id="rmAc"><svg viewBox="-14 -10 28 20"><path d="M13 0 L-7 -2.4 L-9 -8 L-11.5 -8 L-10.5 -2 L-12 -1 L-12 1 L-10.5 2 L-11.5 8 L-9 8 L-7 2.4 Z" /></svg><b>{"WE ARE HERE"}</b></span>            {' '}
<span className="rm-alt">{"MATURITY"}</span>            {' '}
</div>          {' '}
<ol className="rm-cards"><li className="rm-card done" data-k="0" style={{"--n": "0"}} tabIndex="0"><p className="rm-top"><span className="rm-n">{"PHASE 01"}</span><span className="rm-st done">{"Completed"}</span></p><h3>{"Prototype"}</h3><p className="rm-line">{"It runs, in simulation."}</p><ul><li style={{"--m": "0"}}>{"Engine and mission simulation in MATLAB/Simulink"}</li><li style={{"--m": "1"}}>{"Fault injection runs"}</li><li style={{"--m": "2"}}>{"CAN telemetry in software"}</li><li style={{"--m": "3"}}>{"Ground-station dashboard, on demo data"}</li><li style={{"--m": "4"}}>{"First MATLAB app"}</li></ul></li><li className="rm-card now" data-k="1" style={{"--n": "1"}} tabIndex="0"><p className="rm-top"><span className="rm-n">{"PHASE 02"}</span><span className="rm-st now">{"In progress"}</span></p><h3>{"Edge and AI"}</h3><p className="rm-line">{"The intelligence moves on board."}</p><ul><li style={{"--m": "0"}}>{"Raspberry Pi 5 with a CAN interface on the aircraft side"}</li><li style={{"--m": "1"}}>{"Physics-vs-measured check"}</li><li style={{"--m": "2"}}>{"Alerts that explain themselves"}</li><li style={{"--m": "3"}}>{"Remaining-life estimate"}</li><li style={{"--m": "4"}}>{"Dashboard on live simulated data"}</li></ul></li><li className="rm-card next" data-k="2" style={{"--n": "2"}} tabIndex="0"><p className="rm-top"><span className="rm-n">{"PHASE 03"}</span><span className="rm-st next">{"Next"}</span></p><h3>{"Test rig and ground station"}</h3><p className="rm-line">{"Real engine, real ground station."}</p><ul><li style={{"--m": "0"}}>{"Engine test rig with the real ECU/FADEC and CAN, hardware in the loop"}</li><li style={{"--m": "1"}}>{"Twin checked against real engine data"}</li><li style={{"--m": "2"}}>{"Defence-grade ground control station"}</li><li style={{"--m": "3"}}><a className="rm-link" href="#security">{"Secure telemetry: encryption, role-based access, integrity checks"}</a></li></ul></li><li className="rm-card later" data-k="3" style={{"--n": "3"}} tabIndex="0"><p className="rm-top"><span className="rm-n">{"PHASE 04"}</span><span className="rm-st later">{"Later"}</span></p><h3>{"Fleet"}</h3><p className="rm-line">{"From one aircraft to many."}</p><ul><li style={{"--m": "0"}}>{"Fleet-wide health dashboard"}</li><li style={{"--m": "1"}}>{"Shared learning across aircraft, without sharing raw data"}</li><li style={{"--m": "2"}}>{"Twin adaptable to other engines"}</li><li style={{"--m": "3"}}>{"Maintenance (MRO) integration"}</li></ul></li></ol>          {' '}
</div>        {' '}
<p className="rm-foot rv">{"The twin keeps learning: every flight improves the models and adds to the knowledge base."}</p>        {' '}
</div>      {' '}
</section>
  );
}
